/* tslint:disable */
/* eslint-disable */
/**
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The model for a Westpac account.
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * The account reference ID from account list. This is required if the account selection information was provided to you on the consents endpoint.
     * @type {string}
     * @memberof Account
     */
    accountReferenceId?: string;
    /**
     * The account number.
     * @type {string}
     * @memberof Account
     */
    accountNumber?: string;
    /**
     * The account name.
     * @type {string}
     * @memberof Account
     */
    name?: string;
    /**
     * The available balance.
     * @type {string}
     * @memberof Account
     */
    availableBalance?: string;
}
