/* tslint:disable */
/* eslint-disable */
/**
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The enduring consent bank feature
 * @export
 * @interface BankmetadataFeaturesEnduringConsent
 */
export interface BankmetadataFeaturesEnduringConsent {
    /**
     * If enduring consent is disabled, only single payment consents can be issued.
     * @type {boolean}
     * @memberof BankmetadataFeaturesEnduringConsent
     */
    enabled: boolean;
    /**
     * ISO8601 time duration for the maximum allowed enduring consent period, i.e. how long the consent could be used to execute payments for. Appears only if consent_indefinite is false
     * @type {string}
     * @memberof BankmetadataFeaturesEnduringConsent
     */
    maximumConsent?: string;
    /**
     * If the consenting period for payments is indefinite or time-limited by the bank
     * @type {boolean}
     * @memberof BankmetadataFeaturesEnduringConsent
     */
    consentIndefinite?: boolean;
}
