/* tslint:disable */
/* eslint-disable */
/**
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthFlowDetail } from './auth-flow-detail';
import { Bank } from './bank';
import { IdentifierType } from './identifier-type';
import { IdentifierValue } from './identifier-value';
/**
 * The details for a Decoupled flow.
 * @export
 * @interface DecoupledFlow
 */
export interface DecoupledFlow extends AuthFlowDetail {
    /**
     * 
     * @type {Bank}
     * @memberof DecoupledFlow
     */
    bank: Bank;
    /**
     * 
     * @type {IdentifierType}
     * @memberof DecoupledFlow
     */
    identifierType: IdentifierType;
    /**
     * 
     * @type {IdentifierValue}
     * @memberof DecoupledFlow
     */
    identifierValue: IdentifierValue;
    /**
     * A callback URL to call once the consent status has been updated using decoupled flow. Blink will also append the `cid` (the Consent ID) in an additional URL parameter. This is sent to your api as a GET request and will be retried up to 3 times if 5xx errors are received from your server.
     * @type {string}
     * @memberof DecoupledFlow
     */
    callbackUrl?: string;
}


