/* tslint:disable */
/* eslint-disable */
/**
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The refund detail model.
 * @export
 * @interface RefundDetail
 */
export interface RefundDetail {
    /**
     * The payment ID. The payment must have a status of `AcceptedSettlementCompleted`.
     * @type {string}
     * @memberof RefundDetail
     */
    paymentId: string;
    /**
     * The refund type.
     * @type {string}
     * @memberof RefundDetail
     */
    type: RefundDetailTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum RefundDetailTypeEnum {
    AccountNumber = 'account_number',
    PartialRefund = 'partial_refund',
    FullRefund = 'full_refund'
}

